# Basic
title: Kerwin Xiang Liao | 廖翔
subtitle: A Fastidious Maverick in Business Research
welcome_message: 欢迎来到我的魔法世界! 
description: 嗨，我是 GcsSloop，一名来自2.5次元的魔法师，Android自定义View系列文章作者，非著名程序员。
creator: <a href="http://www.GcsSloop.com">@kliao</a>

url: "http://kerwinliao.github.io"

permalink: /:categories/:title

# Format
highlighter: rouge
markdown: kramdown
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", tables]

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: slate

blog_button:
    title: About Me
    description: About me

nav:
    - {title: Research,         in_site: true,  description: research,  url: 'https://github.com/GcsSloop'}
    - {title: Teaching,         in_site: true,  description: teaching,  url: '/timeline'}
    - {title: Curriculum Vitae, in_site: true,  description: cv,        url: '/info/about'}
    - {title: Backgrounds,      in_site: true,  description: backgrounds,        url: '/info/about'}
    


gems:
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-redirect-from

# Pagination
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: GcsSloop
    # duoshuo:
# Social
social:
    linkedin: /in/kerwinlau
    github: GcsSloop
    mail: xiang.liao@grad.moore.sc.edu
    copyright: http://choosealicense.online

# Google Analytics
ga:
    id: UA-82493667-1
    host: www.gcssloop.com
